name: recipley_assignment
description: A new Recipley Assigment project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.15
  material_design_icons_flutter: ^5.0.6996
  google_fonts: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  #  geolocator: ^8.0.0
  permission_handler: ^10.0.0
#  sliding_up_panel: ^2.0.0+1
#  android_id: ^0.0.7
  #  http: ^0.13.0
  dio: ^4.0.6
  intl: ^0.17.0
  #  devicelocale: ^0.5.0
  #  flutter_group_sliver: ^0.0.2
  lottie: ^1.4.2
  app_settings: ^4.1.8
  #  circular_reveal_animation: ^2.0.0
#  new_version: ^0.3.1
  #  android_intent_plus: ^3.1.1+1
  #  flutter_plugin_android_lifecycle: ^2.0.7
  #  stream_transform: ^2.0.0
  vector_math: ^2.1.2
  skeleton_text: ^3.0.0
  #  curved_navigation_bar: ^1.0.1
  cached_network_image: ^3.2.2
#  flutter_staggered_grid_view: ^0.6.2
  #  google_maps_flutter: ^2.1.1
  #  badges: ^2.0.1
  flutter_screenutil: ^5.5.4
  #  flutter_rating_bar: ^4.0.0
  #  get_it: ^4.0.2
  flutter_svg: ^1.1.4
#  device_info_plus: ^4.1.2
  #  fluttertoast: ^6.0.0
  provider: ^6.0.3
#  flutter_staggered_animations: ^1.1.1
  #  scroll_snap_list: ^0.8.4
  #  uuid: ^3.0.6
  #  crypto: ^3.0.2
  #  flutter_google_places: ^0.3.0
  url_launcher: ^6.1.5
  flutter_html: ^3.0.0-alpha.5
  #  camera: ^0.9.4+19
  path_provider: ^2.0.11
  path: ^1.8.2
  ffi: ^2.0.1
  #  geocoding: ^2.0.1
  #  timeline_tile: ^2.0.0
  #  photo_view: ^0.13.0
  #  flutter_device_type: ^0.4.0
  #  flutter_vibrate: ^1.2.0
  #  card_swiper: ^1.0.4
  #  launch_review: ^3.0.0
  visibility_detector: ^0.3.3
  #  html_unescape: ^1.0.2
  connectivity_plus: ^2.3.6+1
#  webview_flutter: ^2.8.0
#  image_picker: ^0.8.3+3
  #  jiffy: ^5.0.0
  #  image_cropper: ^1.4.1
  pull_to_refresh: ^2.0.0
  #  percent_indicator: ^3.4.0
#  scroll_to_index: ^3.0.1
  #  flutter_snake_navigationbar: ^0.5.0
  dropdown_search: ^5.0.2
#  flutter_datetime_picker: ^1.5.1
#  file_picker: ^5.0.1
#  syncfusion_flutter_datepicker: ^20.2.48
#  open_filex: ^4.1.0
  #  location: ^4.2.0
#  expandable: ^5.0.1
#  store_redirect: ^2.0.1
#  package_info_plus: ^1.4.3+1
  #  sliding_clipped_nav_bar: ^3.1.0
  #  readmore: ^2.1.0
#  map_launcher: ^2.3.0+1
  modal_bottom_sheet: ^2.1.2
  #  charts_flutter: ^0.12.0
  #  chart_sparkline: ^1.0.10
  #  fl_chart: ^0.50.1
#  encrypt: ^5.0.1
#  flutter_cached_pdfview: ^0.4.1
  # These packages are for Firebase
  overlay_support: ^2.0.1
  firebase_core: ^2.0.0
  firebase_auth: ^4.2.9
  firebase_database: ^10.0.10
  firebase_storage: ^11.0.9
  flutter_local_notifications: ^9.9.1
  #----------------------------
#  http_certificate_pinning: 2.0.4
#  signature: ^5.3.0
  photo_view: ^0.14.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
